version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    logging:
      driver: awslogs
      options:
        awslogs-group: foodtrucks
        awslogs-region: us-east-1
  web:
    image: prakhar1989/foodtrucks-web
    depends_on:
      - es
    ports:
      - "80:5000" # set to 80
    logging:
      driver: awslogs
      options:
        awslogs-group: foodtrucks
        awslogs-region: us-east-1
