es:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  cpu_shares: 100
  mem_limit: 3621440000
  environment:
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
web:
  image: prakhar1989/foodtrucks-web
  cpu_shares: 100
  mem_limit: 262144000
  ports:
    - "80:5000"
  links:
    - es
